version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: batchdata
    ports:
      - "3399:3306"

  batch-management-service:
    image: batch_management_service_batchmanagement:latest
    container_name: batch-management-service
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3399/batchdata?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_WEBCORS_ALLOWED_ORIGINS: "*"
      SPRING_WEBCORS_ALLOWED_METHODS: "*"
      SPRING_WEBCORS_ALLOWED_HEADERS: "*"
      SPRING_WEBCORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEBCORS_MAX_AGE: "3600"
    restart: always
    depends_on:
      - mysql

